In [15]:
import numpy as np

a=np.array([[1,2,5,3],[3,5,6,7],[10,2,9,7],[7,5,0,1]])
b=np.array([[1,4,6,3],[8,7,9,7],[11,4,18,7],[8,3,9,4]])
print('a:',a)
print('Shape "a":',a.shape)
print('*'*10)

print('b:',b)
print('Shape "b"', b.shape)

a: [[ 1  2  5  3]
 [ 3  5  6  7]
 [10  2  9  7]
 [ 7  5  0  1]]
Shape "a": (4, 4)
**********
b: [[ 1  4  6  3]
 [ 8  7  9  7]
 [11  4 18  7]
 [ 8  3  9  4]]
Shape "b" (4, 4)


In [16]:
#addition
print('a+b :', a+b)

a+b : [[ 2  6 11  6]
 [11 12 15 14]
 [21  6 27 14]
 [15  8  9  5]]


In [17]:
# subtraction
print('a-b :', a-b)

a-b : [[ 0 -2 -1  0]
 [-5 -2 -3  0]
 [-1 -2 -9  0]
 [-1  2 -9 -3]]


In [18]:
#multiplication - elementwise
print('a*b :', a*b)

a*b : [[  1   8  30   9]
 [ 24  35  54  49]
 [110   8 162  49]
 [ 56  15   0   4]]


In [19]:
#dot product multiplication
print('a dot b', a@b)

a dot b [[ 96  47 141  64]
 [165  92 234 114]
 [181 111 303 135]
 [ 55  66  96  60]]


In [20]:
# dot product using numpy.dot
print('a dot b', np.dot(a,b))

a dot b [[ 96  47 141  64]
 [165  92 234 114]
 [181 111 303 135]
 [ 55  66  96  60]]


In [21]:
# matrix division
print('a/b :', a/b)

a/b : [[1.         0.5        0.83333333 1.        ]
 [0.375      0.71428571 0.66666667 1.        ]
 [0.90909091 0.5        0.5        1.        ]
 [0.875      1.66666667 0.         0.25      ]]


In [22]:
#scalar multiplication
print(a*5)

[[ 5 10 25 15]
 [15 25 30 35]
 [50 10 45 35]
 [35 25  0  5]]


In [23]:
# matrix transpose
print('Transpose of a :', a.T)

Transpose of a : [[ 1  3 10  7]
 [ 2  5  2  5]
 [ 5  6  9  0]
 [ 3  7  7  1]]


In [24]:
# matrix determinent
print('Determinant of a :', np.linalg.det(a))

Determinant of a : 840.0000000000007


In [25]:
#matrix rank
print('Rank of a :', np.linalg.matrix_rank(a))

Rank of a : 4


In [27]:
#matrix inverse
print('Inverse of a :', np.linalg.inv(a))

Inverse of a : [[-0.08571429 -0.05714286  0.08571429  0.05714286]
 [ 0.21428571  0.01785714 -0.13095238  0.14880952]
 [ 0.41428571 -0.18214286  0.00238095  0.01547619]
 [-0.47142857  0.31071429  0.0547619  -0.14404762]]


In [29]:
#Eigenvalues & EigenVectors
eigenvalues, eigenvectors = np.linalg.eig(a)
print('Eigenvalues :', eigenvalues)
print('Eigenvectors :', eigenvectors)

Eigenvalues : [18.08462133+0.j         -3.02589947+1.59752338j -3.02589947-1.59752338j
  3.9671776 +0.j        ]
Eigenvectors : [[ 0.32365302+0.j          0.13471503-0.19584352j  0.13471503+0.19584352j
  -0.16209154+0.j        ]
 [ 0.55606989+0.j          0.45387979+0.01923711j  0.45387979-0.01923711j
   0.54183336+0.j        ]
 [ 0.70626068+0.j          0.25131188+0.1930365j   0.25131188-0.1930365j
  -0.63131286+0.j        ]
 [ 0.29534869+0.j         -0.79793452+0.j         -0.79793452-0.j
   0.53064773+0.j        ]]


In [30]:
#matrix concatenation (horizontal)
print('Horizontal Concatenation :', np.hstack((a,b)))

Horizontal Concatenation : [[ 1  2  5  3  1  4  6  3]
 [ 3  5  6  7  8  7  9  7]
 [10  2  9  7 11  4 18  7]
 [ 7  5  0  1  8  3  9  4]]


In [31]:
#matrix concatenation (vertical)
print('Vertical Concatenation :', np.vstack((a,b)))

Vertical Concatenation : [[ 1  2  5  3]
 [ 3  5  6  7]
 [10  2  9  7]
 [ 7  5  0  1]
 [ 1  4  6  3]
 [ 8  7  9  7]
 [11  4 18  7]
 [ 8  3  9  4]]


In [34]:
#matrix reshape
print('Reshape of a :', a.reshape(4,4))

print('*'*5)

#or
print(np.linalg.norm(a))


Reshape of a : [[ 1  2  5  3]
 [ 3  5  6  7]
 [10  2  9  7]
 [ 7  5  0  1]]
*****
21.61018278497431


In [35]:
#Power (element wise power)
print("Power (element wise power)", a**2)

Power (element wise power) [[  1   4  25   9]
 [  9  25  36  49]
 [100   4  81  49]
 [ 49  25   0   1]]
