In [1]:
#import
import numpy as np

In [3]:
#scalar
scalar = np.array(5)
print('Scalar : ', scalar)
print ('Scalar shape',scalar.shape)

Scalar :  5
Scalar shape ()


In [4]:
#Vector
Vector = np.array([1,2,3])
print('Vector : ', Vector)
print ('Vector shape',Vector.shape)

Vector :  [1 2 3]
Vector shape (3,)


In [7]:
#Matrix
matrix=np.array([[1,2,3],[4,5,6]])
print('matrix : ', matrix)
print ('matrix shape',matrix.shape)

matrix :  [[1 2 3]
 [4 5 6]]
matrix shape (2, 3)


In [12]:
#Tensor
tensor=np.array([[[1,2,3],[4,5,6]],[[78,9,4],[4,8,9]]])
print('tensor : ', tensor)
print ('tensor shape',tensor.shape)

tensor :  [[[ 1  2  3]
  [ 4  5  6]]

 [[78  9  4]
  [ 4  8  9]]]
tensor shape (2, 2, 3)
