In [1]:
import numpy as np

In [2]:
#Vector addition
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [3]:
#Vector Subtraction
print(a-b)

[-3 -3 -3]


In [6]:
#Vector Multiplication
print(a*b)
print(a*5)

[ 4 10 18]
[ 5 10 15]


In [7]:
# Dot product
result=np.dot(a,b)
print(result)

32
